### ISSUE TITLE
head / tail

### ISSUE THREAD

**Issue by allee11** [USF-OS/FogOS#1]
Implementing head and tail utility with Andrew Diep.

**Comment by malensek** [comment]
For head and tail, what kind of features will you support? (any flags?)

**Comment by allee11** [comment]
We decided that we wanted to add flags for number of lines, number of bytes, verbose flag which specifies the file name before displaying the data, and a flip a coin flag that flips a coin and if it lands on heads, head works properly. If it lands on tails, it does not work properly.

**Comment by andrewdiep1** [comment]
The flip a coin flag would conduct a simple coin flip, print out the result (heads 49%, tails 49%, or undecided 2%), and confirm whether or not you made the right call.

Ex: head -flip

Coin flip result: Undecided -> Oops! Looks like the coin got stuck in a quantum loop between heads and tails. Let's try flipping again and hope the universe makes up its mind this time!" 🪙🤷‍♂️🪙

**Comment by malensek** [comment]
Sounds good!
