### ISSUE TITLE
Array Operations

### ISSUE THREAD

**Issue by atanaspatterson** [USF-OS/FogOS#12]
Rich and I are planning on doing some array-related operations, likely with an `array.c `and `array.h` files. Examples of operations would include:

- Sorting/Searching algorithms
- Union/Intersection of 2 arrays
- Deleting/Adding at index

**Comment by atanaspatterson** [comment]
Update: I believe Rich might not be in it anymore (😔)

**Comment by malensek** [comment]
:+1:
