### ISSUE TITLE
comm command

### ISSUE THREAD

**Issue by kat-le** [USF-OS/FogOS#13]
I would like to add the “comm” command to the FogOS. It will compare 2 files and output the lines that are unique to each file and lines that are common to each file. 

Goals:
- Display the output into 3 columns 
     Column 1: lines unique to first file
     Column 2: lines unique to second file
     Column 3: lines that appear in both files
- Include flags:
     -1: omit first column from output
     -2: omit second column from output
     -3: omit third column from output

**Comment by malensek** [comment]
Sounds good to me! Good idea.
