### ISSUE TITLE
scheduling algorithms/Linklist

### ISSUE THREAD

**Issue by MessiBest07** [USF-OS/FogOS#15]
I want to decide which process or thread should get the resource out of the limited compute resources. I wonder if the existing code contains scheduling algorithm? If not, maybe I can try some simple scheduling algorithms？Such as FCFS, SJF, HRRN. Or Create some single/double linked lists

**Comment by malensek** [comment]
That is a cool idea, but would have to be implemented completely in kernel space. Stay tuned because we have a scheduling assignment coming soon.

**Comment by malensek** [comment]
(Closing, please file a new issue)
