### ISSUE TITLE
history 

### ISSUE THREAD

**Issue by ainsleeSmith** [USF-OS/FogOS#18]
Hi! Im FogOS so far there is no way to go back and see the previous commands you type so @lghimire and I propose a history command where you can see the previous commands you can type. In this proposal we will show up to 100 commands that were typed by the user in the OS. We will be editing the shell for this.

**Comment by malensek** [comment]
Sounds great!

**Comment by malensek** [comment]
I was thinking this one over a bit more and there are a few requirements I would like to add to make sure this is enough work:
* The history needs be FIFO, with the oldest items getting popped off the list. When you run the history command, though, it displays in chronological order from most recent command to the oldest. (this is how most shells do it)
* While it's fine to support 100 commands as a default, the size of the command list should be configurable / dynamic. I want to avoid having a hard-coded array in the shell. The cool thing about this feature is you could set it to, say, 5 or 10 to see that the previous feature is working correctly.
* Saving the history to a file on the disk, so if you restart the OS you can still see the history.

Let me know what you think.
