### ISSUE TITLE
Date command

### ISSUE THREAD

**Issue by Ndewedo-Newbury** [USF-OS/FogOS#19]
I would like to implement the date command which would display Today's date and include other features. Will also implement a new flag called "set" which will save one's personal date output format configurations.

flags:
-R, --rfc-email
              output date and time in RFC 5322 format.  Example: Mon, 14
              Aug 2006 02:34:56 -0600
 --rfc-3339=FMT
              output date/time in RFC 3339 format.  FMT='date',
              'seconds', or 'ns' for date and time to the indicated
              precision.  Example: 2006-08-14 02:34:56-06:0
-r, --reference=FILE (IF POSSIBLE)
              display the last modification time of FILE
-u, --utc, --universal
              print or set Coordinated Universal Time (UTC)

--help display this help and exit

Format option will be configured as shown on man pages [here](https://www.man7.org/linux/man-pages/man1/date.1.html)
Not all options will be completed, more of that in the help flag

**Comment by malensek** [comment]
Sounds good to me. It should be possible to basically reverse Lab 3 to be able to set the time (when you're implementing --utc)
