### ISSUE TITLE
sort command

### ISSUE THREAD

**Issue by sghahghahi** [USF-OS/FogOS#2]
Implement a `sort` tool with multiple flags to sort lines of text and files.

<strong>Contributors:</strong>
Shyon Ghahghahi
Amin Joseph

**Comment by malensek** [comment]
That sounds good, what flags do you think you'll be able to support? Are you planning on using a particular sorting algorithm?

**Comment by sghahghahi** [comment]
We plan on supporting the following flags:

- `-n` : numeric sort (default sort is lexicographic)
- `-r` : sort in reverse order
- `-u` : only sort unique values
- `-b` : ignore leading blanks
- `-f` : ignore case

We plan on using a combination of both insertion sort and merge sort depending on the size of the input data.
