### ISSUE TITLE
strrev(), palindrome detection, and regex()

### ISSUE THREAD

**Issue by ajcatoiu** [USF-OS/FogOS#20]
Students:
Andrew
Phong

Will implement the following functions:
strrev() - Takes a string and outputs it in reverse. Will likely be working in the kernel's string.c file.
checkPal() - Will utilize strrev() to detect palindromes in strings. Palindromes will be displayed on their own line. Unsure how the user will run it (maybe with providing a command "checkPal" and then a string argument OR just executing the function in a user space test program and possibly read from a text file). 
regex() - Searches for a particular sequence of characters in a string. For example, we have a string of "qwertyuiop" and we want to search for the pattern of "tyu", then the function will return true, else return false.

**Comment by malensek** [comment]
The scope of this proposal is a bit too limited to be a full project. strrev is interesting but probably ~3 lines of code, although the user space utility definitely helps boost its usefulness.

There is already basic regex support (beyond even a string match) in `user/grep.c`

**Comment by malensek** [comment]
We chatted a bit today about adding md5 or some other cryptographic hash utility to the OS. Here's an implementation of SHA-1:
* [sha1.c.txt](https://github.com/USF-OS/FogOS/files/14315490/sha1.c.txt)
* [sha1.h.txt](https://github.com/USF-OS/FogOS/files/14315491/sha1.h.txt)

You can compare it with the `sha1sum` utility on Linux. This will take a bit of work to port to xv6, particularly getting the types right
