### ISSUE TITLE
Character Functions

### ISSUE THREAD

**Issue by knchan03** [USF-OS/FogOS#22]
Implement some simple character functions:
- IsDigit() / IsAlpha()
- IsUpper() / IsLower() / ToUpper() / ToLower()
- IsPunct() / IsSpace()
- CharDet() function to determine if char is greater than a given ASCII # or character or less than given ASCII character
  - CharDet(char *str, char c, int g, int l) 

- Implement strpbrk()

- FindIndexes() function that could determine what indices a character lies in a string
- CharacterCount() to determine # of character occurences in a string
- StringCount() to to determine # of substring occurences in a string

**Comment by malensek** [comment]
Sounds good. I'd probably skip CharDet, wouldn't you be able to just check a > b  or a < b already?
