### ISSUE TITLE
md5sum

### ISSUE THREAD

**Issue by ajcatoiu** [USF-OS/FogOS#24]
Participants:
Andrew
Phong

Hi Matthew, we liked your idea of verifying changes within a file with hashed strings. We will be implementing the md5sum utility.

**Comment by malensek** [comment]
From our chat the other day, here's an implementation of SHA-1:
* [sha1.c.txt](https://github.com/USF-OS/FogOS/files/14315490/sha1.c.txt)
* [sha1.h.txt](https://github.com/USF-OS/FogOS/files/14315491/sha1.h.txt)

You can compare it with the `sha1sum` utility on Linux. This will take a bit of work to port to xv6, particularly getting the types right
