### ISSUE TITLE
Directory Size Viewing tool/File Permissions View 

### ISSUE THREAD

**Issue by MessiBest07** [USF-OS/FogOS#25]
implements a command to quickly calculate and display the total size of all files in a directory and its subdirectories/A simple command line tool that lists file permissions and provides an easy way to modify them

**Comment by malensek** [comment]
Cool, so kind of like ‘du’ command? Maybe you could also support displaying the sizes with human readable units, bytes could be default but you could display KB MB etc. The man page for du would have some other ideas for additional features. 

for the second part, xv6 doesn’t have permissions so we can’t do it (yet :-))
