### ISSUE TITLE
Project 1 - Add New Utility - cksum

### ISSUE THREAD

**Issue by marcusaltman** [USF-OS/FogOS#4]
I want to add the cksum command to FogOS

**Comment by malensek** [comment]
Sounds like a good idea, plus this will be easy to test because you can compare it with the Linux cksum.

**Comment by marcusaltman** [comment]
I will implement cksum as follows:

1. Command Syntax: cksum [File_Name]
2. Calculates the checksum using a cyclical redundancy check algorithm
3. Determines the size of the file in bytes
4. Displays the checksum, file size, and file name on the console
