### ISSUE TITLE
Add kill command

### ISSUE THREAD

**Issue by mvvillarrealblozis** [USF-OS/FogOS#57]
`kill` sends a signal to terminate a process identified by its process ID (PID). If called with a single argument (the PID), it will send a termination signal (SIGKILL) to that process. If the process is running, it will be terminated immediately.

If the -s flag is passed with an additional signal number argument, the specified signal will be sent to the process instead. By default, the command sends a termination signal (SIGKILL). Other signals like SIGTERM can be implemented for graceful termination.

**Usage:**

```
kill <pid>
kill -s <signal> <pid>
```

-s: Specifies a signal to send instead of the default termination signal.

**Libc changes:**

Add kill system call to interact with the process management system.

**Future Development:**
Change the name to something funny

**Comment by geoweb999** [comment]
Happy to be one of the student code reviewers
