### ISSUE TITLE
Math library 

### ISSUE THREAD

**Issue by nogagottlieb** [USF-OS/FogOS#6]
Param and I (Noga) want to add the math library to our FogOS.

**Comment by malensek** [comment]
I like the idea. Ideally this could be a separate `math.h` and `math.c` that user programs can include if they need it. 

Would you be implementing everything in the standard C math library? A subset?

**Comment by nogagottlieb** [comment]
A subset will probably be a better idea since there are over 20 functions. How many are you expecting us to implement?
