### ISSUE TITLE
Adding df command

### ISSUE THREAD

**Issue by mvvillarrealblozis** [USF-OS/FogOS#63]
`df` or diskfree reports the amount of disk space used and available on the system's mounted filesystems. When run without arguments, it will display this information for all mounted filesystems. If one or more paths are provided as arguments, it will only display information for the filesystems associated with those paths.

The output includes details such as total disk size, used space, available space, and percentage of the disk used.

**Usage:**

```
diskfree
diskfree <path>
```

-h: Outputs sizes in human-readable format (KB, MB, GB, etc.) rather than blocks.
-i: Displays inode usage information instead of block usage.

If the given path points to a directory, diskfree will traverse the directory structure to find the root of the filesystem and report on that.

**Libc changes:**

Add statvfs system call to gather information about the filesystem.

**Future Development:**

Implement file type filters (e.g., only report on specific filesystem types).
Add color-coding to highlight filesystems nearing capacity.

**Comment by malensek** [comment]
This sounds great. Let me know if you run into any issues with getting the FS info out of kernel space.
