### ISSUE TITLE
Add watch command to run a command repeatedly at a specified interval and display the output.

### ISSUE THREAD

**Issue by Unbanneduser** [USF-OS/FogOS#66]
This utility allows users to run a command repeatedly at a specified interval and display the output. It's useful for monitoring system metrics or changes in real-time.
Team: zijie guo, yahvi

**Comment by malensek** [comment]
This is a good idea for a project but needs more detail on what will actually be implemented: just the watch command itself is maybe a 5-minute job, so please expand this with the features you will support.

**Comment by Unbanneduser** [comment]
We are going to add these functions for extensions:
1. Customizable Interval 
2. Output Formatting Options
3. Log Output to File
4. Alerts and Notifications
5. Pause and Resume Functionality
